//go:build !ignore_autogenerated

// Code generated by controller-gen style DeepCopy helpers. DO NOT EDIT casually.
// Hand-written to mirror controller-gen output so the project builds without
// running code generation.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out.
func (in *PodRef) DeepCopyInto(out *PodRef) {
	*out = *in
}

// DeepCopy returns a deep copy.
func (in *PodRef) DeepCopy() *PodRef {
	if in == nil {
		return nil
	}
	out := new(PodRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
}

// DeepCopy returns a deep copy.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *GPUCheckpointSpec) DeepCopyInto(out *GPUCheckpointSpec) {
	*out = *in
	out.PodRef = in.PodRef
	out.Storage = in.Storage
}

// DeepCopy returns a deep copy.
func (in *GPUCheckpointSpec) DeepCopy() *GPUCheckpointSpec {
	if in == nil {
		return nil
	}
	out := new(GPUCheckpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *GPUCheckpointStatus) DeepCopyInto(out *GPUCheckpointStatus) {
	*out = *in
	if in.LastCheckpointTime != nil {
		in, out := &in.LastCheckpointTime, &out.LastCheckpointTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy.
func (in *GPUCheckpointStatus) DeepCopy() *GPUCheckpointStatus {
	if in == nil {
		return nil
	}
	out := new(GPUCheckpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *GPUCheckpoint) DeepCopyInto(out *GPUCheckpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy.
func (in *GPUCheckpoint) DeepCopy() *GPUCheckpoint {
	if in == nil {
		return nil
	}
	out := new(GPUCheckpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a runtime.Object copy.
func (in *GPUCheckpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *GPUCheckpointList) DeepCopyInto(out *GPUCheckpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPUCheckpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy.
func (in *GPUCheckpointList) DeepCopy() *GPUCheckpointList {
	if in == nil {
		return nil
	}
	out := new(GPUCheckpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a runtime.Object copy.
func (in *GPUCheckpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
