//go:build !ignore_autogenerated

// Hand-written deepcopy for the WorkloadCheckpoint types. Equivalent to what
// controller-gen would emit; regenerate with `make generate` if you change the
// types and have controller-gen available.
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out.
func (in *WorkloadTargetRef) DeepCopyInto(out *WorkloadTargetRef) {
	*out = *in
}

// DeepCopy returns a deep copy.
func (in *WorkloadTargetRef) DeepCopy() *WorkloadTargetRef {
	if in == nil {
		return nil
	}
	out := new(WorkloadTargetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *WorkloadCheckpointSpec) DeepCopyInto(out *WorkloadCheckpointSpec) {
	*out = *in
	out.WorkloadRef = in.WorkloadRef
	in.Storage.DeepCopyInto(&out.Storage)
	if in.PodSelector != nil {
		out.PodSelector = in.PodSelector.DeepCopy()
	}
	if in.RequireGPU != nil {
		v := *in.RequireGPU
		out.RequireGPU = &v
	}
}

// DeepCopy returns a deep copy.
func (in *WorkloadCheckpointSpec) DeepCopy() *WorkloadCheckpointSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadCheckpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *TargetStatus) DeepCopyInto(out *TargetStatus) {
	*out = *in
}

// DeepCopy returns a deep copy.
func (in *TargetStatus) DeepCopy() *TargetStatus {
	if in == nil {
		return nil
	}
	out := new(TargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *WorkloadCheckpointStatus) DeepCopyInto(out *WorkloadCheckpointStatus) {
	*out = *in
	if in.Targets != nil {
		l := make([]TargetStatus, len(in.Targets))
		copy(l, in.Targets)
		out.Targets = l
	}
	if in.StartTime != nil {
		out.StartTime = in.StartTime.DeepCopy()
	}
	if in.CompletionTime != nil {
		out.CompletionTime = in.CompletionTime.DeepCopy()
	}
	if in.Conditions != nil {
		c := make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&c[i])
		}
		out.Conditions = c
	}
}

// DeepCopy returns a deep copy.
func (in *WorkloadCheckpointStatus) DeepCopy() *WorkloadCheckpointStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadCheckpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *WorkloadCheckpoint) DeepCopyInto(out *WorkloadCheckpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy.
func (in *WorkloadCheckpoint) DeepCopy() *WorkloadCheckpoint {
	if in == nil {
		return nil
	}
	out := new(WorkloadCheckpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a runtime.Object copy.
func (in *WorkloadCheckpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *WorkloadCheckpointList) DeepCopyInto(out *WorkloadCheckpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]WorkloadCheckpoint, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

// DeepCopy returns a deep copy.
func (in *WorkloadCheckpointList) DeepCopy() *WorkloadCheckpointList {
	if in == nil {
		return nil
	}
	out := new(WorkloadCheckpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a runtime.Object copy.
func (in *WorkloadCheckpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
